# standard jekyll configuration

permalink: pretty
exclude: ['Rakefile', 'config.rb', 'vendor']
markdown: kramdown
pygments: true

# configuration required for some pages

domain: blog.luxifer.fr
title: Blog de Florent Viel
author: Florent Viel
email: florent.viel69@gmail.com
include: [images,font]
paginate: 5
lsi: false

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-438897-2

disqus:
  id: luxifer
