# standard jekyll configuration

permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock']
markdown: redcarpet
highlighter: pygments
gems: [jekyll-geo-pattern]

# configuration required for some pages

domain: blog.luxifer.fr
title: Blog de Florent Viel
author: Florent Viel
description: Blog centré sur le développement php et symfony2
email: florent.viel69@gmail.com
include: [images,font]
paginate: 5
lsi: false
icon: /assets/images/icon.png

# specific configuration

google_analytics:
  account: UA-438897-2

disqus:
  id: luxifer

author:
  name: Florent Viel
  url: https://plus.google.com/+FlorentViel

copyright:
  author:   Florent Viel
  url:      http://florentviel.com
  type_title:   Tous droits réservés
  type_url: http://creativecommons.org/licenses/by-nc/2.5

github:
  repo: https://github.com/luxifer/blog
