# standard jekyll configuration

permalink: date
exclude: ['Rakefile', 'config.rb']
markdown: maruku
pygments: true

# configuration required for some pages

domain: blog.luxifer.fr
title: Blog de Florent Viel
author: Florent Viel
email: florent.viel69@gmail.com
include: [images]

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

disqus:
  id: luxifer
